Repository the-vision/jarvis-telegram, pull requests merged in 2020-05, with the labels that each got.

#75 Added new module: meme
  bot.py
  modules.py
Labels: easy, gssoc20

#52 Added ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/pull_request_template.md
Labels: beginner, gssoc20

#53 Added CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: beginner, gssoc20

#18 Add new module: help
  modules.py
Labels: beginner, gssoc20

#62 Added new intent: wiki
  modules.py
  requirements.txt
Labels: gssoc20, medium

#73 Added new module: anime
  modules.py
Labels: easy, gssoc20

#40 feat: translate module
  modules.py
Labels: easy, gssoc20

#65 Added the time module
  modules.py
Labels: easy, gssoc20

#58 Added new intent: currency
  modules.py
Labels: easy, gssoc20

#77 Added new module: Video
  example.env
  modules.py
Labels: easy, gssoc20

#63 Added new module: news
  modules.py
Labels: gssoc20, medium
